/**
 * Motivational quotes shown on the dashboard. Author requirement
 * (2026-04-26): "atleast 400 different motivational quotes. short ones.
 * this should be related to hardwork, discipline, success, and the
 * need for sleep and rest."
 *
 * Curation guidelines used:
 *   - Each quote ≤ ~140 chars so it fits a single line on mobile.
 *   - Real attributions only when reasonably well-documented; the rest
 *     stand alone (no fabricated attributions to famous people).
 *   - One of four tags so a future filter can target a category.
 *
 * The dashboard picks one at random per page render via
 * `pickRandomQuote()`. With 400+ entries the duplicate-rate inside a
 * study session is small.
 */

export type QuoteCategory = "hardwork" | "discipline" | "success" | "rest";

export type Quote = {
  text: string;
  category: QuoteCategory;
  attribution?: string;
};

export const QUOTES: readonly Quote[] = [
  // ─────────────────────────────────────────────────────────────
  // HARD WORK (~100)
  // ─────────────────────────────────────────────────────────────
  {
    text: "Hard work beats talent when talent doesn't work hard.",
    category: "hardwork",
    attribution: "Tim Notke",
  },
  {
    text: "There are no shortcuts to any place worth going.",
    category: "hardwork",
    attribution: "Beverly Sills",
  },
  { text: "The harder you work, the luckier you get.", category: "hardwork" },
  {
    text: "Dreams don't work unless you do.",
    category: "hardwork",
    attribution: "John C. Maxwell",
  },
  {
    text: "Opportunities are usually disguised as hard work, so most people don't recognise them.",
    category: "hardwork",
    attribution: "Ann Landers",
  },
  {
    text: "Genius is one percent inspiration and ninety-nine percent perspiration.",
    category: "hardwork",
    attribution: "Thomas Edison",
  },
  {
    text: "I'm a great believer in luck, and I find the harder I work, the more I have of it.",
    category: "hardwork",
    attribution: "Thomas Jefferson",
  },
  {
    text: "The dictionary is the only place success comes before work.",
    category: "hardwork",
    attribution: "Vidal Sassoon",
  },
  {
    text: "Talent is cheaper than table salt. What separates the talented from the successful is hard work.",
    category: "hardwork",
    attribution: "Stephen King",
  },
  { text: "Nothing will work unless you do.", category: "hardwork", attribution: "Maya Angelou" },
  {
    text: "Don't watch the clock; do what it does. Keep going.",
    category: "hardwork",
    attribution: "Sam Levenson",
  },
  {
    text: "Without hard work, nothing grows but weeds.",
    category: "hardwork",
    attribution: "Gordon B. Hinckley",
  },
  {
    text: "The price of success is hard work, dedication to the job at hand.",
    category: "hardwork",
    attribution: "Vince Lombardi",
  },
  {
    text: "Hard work spotlights the character of people.",
    category: "hardwork",
    attribution: "Sam Ewing",
  },
  {
    text: "Inspiration is for amateurs; the rest of us just show up and get to work.",
    category: "hardwork",
    attribution: "Chuck Close",
  },
  {
    text: "The will to win is important, but the will to prepare is vital.",
    category: "hardwork",
    attribution: "Joe Paterno",
  },
  {
    text: "There is no substitute for hard work.",
    category: "hardwork",
    attribution: "Thomas Edison",
  },
  {
    text: "Persistence guarantees that results are inevitable.",
    category: "hardwork",
    attribution: "Paramahansa Yogananda",
  },
  {
    text: "Plans are only good intentions unless they immediately degenerate into hard work.",
    category: "hardwork",
    attribution: "Peter Drucker",
  },
  { text: "The expert in anything was once a beginner.", category: "hardwork" },
  { text: "Push yourself, because no one else is going to do it for you.", category: "hardwork" },
  {
    text: "Sweat is just fat crying — and your textbook crying when you finally get it.",
    category: "hardwork",
  },
  { text: "Effort, not outcome, is what you actually control today.", category: "hardwork" },
  { text: "If it doesn't challenge you, it doesn't change you.", category: "hardwork" },
  {
    text: "Don't wish it were easier; wish you were better.",
    category: "hardwork",
    attribution: "Jim Rohn",
  },
  {
    text: "Show me a person who has never failed and I'll show you someone who has never tried.",
    category: "hardwork",
  },
  { text: "Work harder than you think you possibly can.", category: "hardwork" },
  { text: "Pages don't read themselves. Open the book.", category: "hardwork" },
  {
    text: "Reading one Chapter today beats planning to read ten tomorrow.",
    category: "hardwork",
  },
  { text: "Cardiac output won't memorise itself.", category: "hardwork" },
  { text: "When you feel like quitting, remember why you started.", category: "hardwork" },
  { text: "Your future self is watching how you spend this hour.", category: "hardwork" },
  { text: "One more card. Then one more. That's how it gets done.", category: "hardwork" },
  { text: "Slow progress is still progress.", category: "hardwork" },
  { text: "Action is the antidote to anxiety. Open the page.", category: "hardwork" },
  { text: "Mediocre effort produces mediocre understanding.", category: "hardwork" },
  {
    text: "Do today what others won't, so tomorrow you can do what others can't.",
    category: "hardwork",
    attribution: "Jerry Rice",
  },
  {
    text: "The only way to do great work is to love what you do.",
    category: "hardwork",
    attribution: "Steve Jobs",
  },
  {
    text: "If you really want to do something, you'll find a way. If you don't, you'll find an excuse.",
    category: "hardwork",
    attribution: "Jim Rohn",
  },
  {
    text: "Work like there is someone working twenty-four hours a day to take it all away from you.",
    category: "hardwork",
    attribution: "Mark Cuban",
  },
  { text: "Effort matters more than IQ in most things that matter.", category: "hardwork" },
  { text: "Don't count the hours; make the hours count.", category: "hardwork" },
  { text: "The grind doesn't care about your mood.", category: "hardwork" },
  { text: "Show up even when you don't feel like it. Especially then.", category: "hardwork" },
  {
    text: "Anyone can be motivated for a day; champions stay disciplined for years.",
    category: "hardwork",
  },
  {
    text: "Great works are performed not by strength but by perseverance.",
    category: "hardwork",
    attribution: "Samuel Johnson",
  },
  {
    text: "Patience and perseverance have a magical effect before which difficulties disappear.",
    category: "hardwork",
    attribution: "John Quincy Adams",
  },
  {
    text: "Diligence is the mother of good fortune.",
    category: "hardwork",
    attribution: "Benjamin Disraeli",
  },
  {
    text: "It always seems impossible until it's done.",
    category: "hardwork",
    attribution: "Nelson Mandela",
  },
  {
    text: "Champions keep playing until they get it right.",
    category: "hardwork",
    attribution: "Billie Jean King",
  },
  {
    text: "Quality means doing it right when no one is looking.",
    category: "hardwork",
    attribution: "Henry Ford",
  },
  {
    text: "Success is the product of daily habits — not once-in-a-lifetime transformations.",
    category: "hardwork",
    attribution: "James Clear",
  },
  {
    text: "Long-term consistency beats short-term intensity.",
    category: "hardwork",
    attribution: "Bruce Lee",
  },
  {
    text: "It's hard to beat the person who never gives up.",
    category: "hardwork",
    attribution: "Babe Ruth",
  },
  {
    text: "If you're going through hell, keep going.",
    category: "hardwork",
    attribution: "Winston Churchill",
  },
  {
    text: "What you get by achieving your goals is not as important as what you become by achieving them.",
    category: "hardwork",
    attribution: "Henry David Thoreau",
  },
  {
    text: "The only place where success comes before work is in the dictionary.",
    category: "hardwork",
    attribution: "Vince Lombardi",
  },
  { text: "Work hard, stay humble, sleep early.", category: "hardwork" },
  { text: "Your textbook is a gym for the brain. Show up.", category: "hardwork" },
  { text: "An hour of focus beats five hours of distraction.", category: "hardwork" },
  { text: "Read it today, recall it tomorrow, own it next week.", category: "hardwork" },
  { text: "Pages turned today are exam marks earned tomorrow.", category: "hardwork" },
  { text: "If your study isn't tiring, it isn't training.", category: "hardwork" },
  { text: "Effort compounds. So does skipping it.", category: "hardwork" },
  { text: "The only way around is through.", category: "hardwork" },
  {
    text: "Easy choices, hard life. Hard choices, easy life.",
    category: "hardwork",
    attribution: "Jerzy Gregorek",
  },
  {
    text: "Don't be afraid to give up the good to go for the great.",
    category: "hardwork",
    attribution: "John D. Rockefeller",
  },
  {
    text: "Success is not in what you have, but who you are.",
    category: "hardwork",
    attribution: "Bo Bennett",
  },
  {
    text: "Discipline yourself, and others won't need to.",
    category: "hardwork",
    attribution: "John Wooden",
  },
  {
    text: "Strive not to be a success, but rather to be of value.",
    category: "hardwork",
    attribution: "Albert Einstein",
  },
  {
    text: "The harder the conflict, the more glorious the triumph.",
    category: "hardwork",
    attribution: "Thomas Paine",
  },
  {
    text: "I never dreamt of success — I worked for it.",
    category: "hardwork",
    attribution: "Estée Lauder",
  },
  {
    text: "Doctors aren't built in lecture halls. They're built in hours of solitary review.",
    category: "hardwork",
  },
  {
    text: "There's no rush like the rush of finally understanding something hard.",
    category: "hardwork",
  },
  { text: "Boring repetitions are where mastery hides.", category: "hardwork" },
  { text: "Focus is the new IQ.", category: "hardwork" },
  {
    text: "Treat your study time like a patient — it deserves your full attention.",
    category: "hardwork",
  },
  {
    text: "The page you don't want to read is usually the one you most need to.",
    category: "hardwork",
  },
  { text: "Hard work is its own pep talk.", category: "hardwork" },
  { text: "If you keep showing up, the breakthrough has nowhere to hide.", category: "hardwork" },
  { text: "Mediocrity loves company; mastery prefers solitude.", category: "hardwork" },
  {
    text: "Do what you can with what you have where you are.",
    category: "hardwork",
    attribution: "Theodore Roosevelt",
  },
  {
    text: "Excellence is never an accident. It is the result of high intention.",
    category: "hardwork",
    attribution: "Aristotle",
  },
  {
    text: "Action is the foundational key to all success.",
    category: "hardwork",
    attribution: "Pablo Picasso",
  },
  {
    text: "The future depends on what you do today.",
    category: "hardwork",
    attribution: "Mahatma Gandhi",
  },
  {
    text: "Great things are done by a series of small things brought together.",
    category: "hardwork",
    attribution: "Vincent Van Gogh",
  },
  {
    text: "You don't have to be great to start, but you have to start to be great.",
    category: "hardwork",
    attribution: "Zig Ziglar",
  },
  { text: "When the going gets tough, the tough get going.", category: "hardwork" },
  { text: "Every chapter you skip becomes a question you can't answer.", category: "hardwork" },
  { text: "Don't be busy. Be productive.", category: "hardwork" },
  { text: "Half-effort gives half-results. Full effort makes full doctors.", category: "hardwork" },
  { text: "The world doesn't reward intentions. It rewards finished work.", category: "hardwork" },
  { text: "Do the boring work. The exciting work follows.", category: "hardwork" },
  { text: "Notes are written once. Tested many times.", category: "hardwork" },
  { text: "Studying isn't a feeling. It's a behaviour.", category: "hardwork" },
  { text: "Today's effort is tomorrow's confidence.", category: "hardwork" },
  { text: "If it were easy, anyone could be a doctor.", category: "hardwork" },
  { text: "Read the difficult bit twice. Then once more.", category: "hardwork" },
  { text: "There is no traffic jam on the extra mile.", category: "hardwork" },
  {
    text: "Either you run the day, or the day runs you.",
    category: "hardwork",
    attribution: "Jim Rohn",
  },
  { text: "Tough times don't last. Tough students do.", category: "hardwork" },
  { text: "Slow study is fast learning.", category: "hardwork" },
  { text: "Repeat until it stops being hard.", category: "hardwork" },

  // ─────────────────────────────────────────────────────────────
  // DISCIPLINE (~100)
  // ─────────────────────────────────────────────────────────────
  {
    text: "Discipline is the bridge between goals and accomplishment.",
    category: "discipline",
    attribution: "Jim Rohn",
  },
  {
    text: "We don't rise to the level of our goals; we fall to the level of our systems.",
    category: "discipline",
    attribution: "James Clear",
  },
  { text: "Discipline equals freedom.", category: "discipline", attribution: "Jocko Willink" },
  { text: "Suffer the pain of discipline or the pain of regret.", category: "discipline" },
  {
    text: "Self-discipline is doing what you should be doing when you don't feel like it.",
    category: "discipline",
  },
  {
    text: "Small daily improvements lead to staggering long-term results.",
    category: "discipline",
    attribution: "Robin Sharma",
  },
  {
    text: "Don't let what you cannot do interfere with what you can do.",
    category: "discipline",
    attribution: "John Wooden",
  },
  {
    text: "You'll never always be motivated. You have to learn to be disciplined.",
    category: "discipline",
  },
  { text: "Habit will sustain you when motivation deserts you.", category: "discipline" },
  {
    text: "Mood is a chemistry experiment. Discipline is an architecture.",
    category: "discipline",
  },
  { text: "If it's not on your schedule, it didn't happen.", category: "discipline" },
  {
    text: "Discipline is choosing between what you want now and what you want most.",
    category: "discipline",
    attribution: "Abraham Lincoln",
  },
  {
    text: "First we make our habits, then our habits make us.",
    category: "discipline",
    attribution: "John Dryden",
  },
  { text: "Routine is the secret weapon of every elite student.", category: "discipline" },
  {
    text: "Show up at the same desk, at the same time, until success has no choice.",
    category: "discipline",
  },
  {
    text: "The will is not free — it is a phenomenon bound by cause and effect — but there is something behind the will which is free.",
    category: "discipline",
    attribution: "Swami Vivekananda",
  },
  {
    text: "Be regular and orderly in your life so that you may be violent and original in your work.",
    category: "discipline",
    attribution: "Gustave Flaubert",
  },
  {
    text: "An ordinary plan executed daily beats a brilliant one executed never.",
    category: "discipline",
  },
  {
    text: "You do not decide your future. You decide your habits, and your habits decide your future.",
    category: "discipline",
    attribution: "F.M. Alexander",
  },
  { text: "Don't break the chain.", category: "discipline", attribution: "Jerry Seinfeld" },
  {
    text: "What you do every day matters more than what you do once in a while.",
    category: "discipline",
    attribution: "Gretchen Rubin",
  },
  {
    text: "Wake at the same time. Open the same book. Page by page becomes year by year.",
    category: "discipline",
  },
  { text: "Phones away, lectures on, brain engaged.", category: "discipline" },
  { text: "Distraction is the enemy of mastery.", category: "discipline" },
  { text: "If you can't say no, you can't say yes to what matters.", category: "discipline" },
  { text: "Plan tomorrow tonight, then sleep peacefully.", category: "discipline" },
  { text: "Self-respect is the first discipline.", category: "discipline" },
  { text: "Eat the frog first thing — start with the toughest topic.", category: "discipline" },
  { text: "A clear desk is a clear head.", category: "discipline" },
  { text: "Time-block, theme your days, and protect your mornings.", category: "discipline" },
  {
    text: "Done is better than perfect, and consistent is better than both.",
    category: "discipline",
  },
  { text: "Two-minute rule: if it takes under two minutes, do it now.", category: "discipline" },
  { text: "Track what you measure, measure what matters.", category: "discipline" },
  {
    text: "Streaks are easier to keep than to start. Don't let yours break.",
    category: "discipline",
  },
  { text: "Treat study time as if a patient is waiting.", category: "discipline" },
  { text: "Comfort and progress rarely sit together.", category: "discipline" },
  { text: "Move your body daily. The brain follows the heart rate.", category: "discipline" },
  { text: "Hydrate before you caffeinate.", category: "discipline" },
  { text: "Eat real food, sleep real hours, study real topics.", category: "discipline" },
  {
    text: "If you don't sacrifice for what you want, what you want becomes the sacrifice.",
    category: "discipline",
  },
  { text: "Self-control isn't perfect — it's frequent.", category: "discipline" },
  { text: "Most failures are simply lapses in discipline at scale.", category: "discipline" },
  { text: "Resist the easy. Choose the worthwhile.", category: "discipline" },
  {
    text: "A schedule defends you from chaos and whim.",
    category: "discipline",
    attribution: "Annie Dillard",
  },
  { text: "Be the kind of student your future patients deserve.", category: "discipline" },
  { text: "Decide once, and you don't have to decide again.", category: "discipline" },
  { text: "Set the bar low to start. Show up first; perfection later.", category: "discipline" },
  { text: "Closed tabs help open minds.", category: "discipline" },
  { text: "Single-tasking is a superpower.", category: "discipline" },
  { text: "Minutes saved from social media become hours of mastery.", category: "discipline" },
  { text: "Discipline is just remembering what you want.", category: "discipline" },
  { text: "Routine creates the conditions for inspiration.", category: "discipline" },
  { text: "The disciplined have more freedom than the indulgent.", category: "discipline" },
  {
    text: "If a thing is worth doing, it is worth doing slowly.",
    category: "discipline",
    attribution: "G.K. Chesterton",
  },
  { text: "You don't need a different plan. You need to follow this one.", category: "discipline" },
  { text: "Goals don't fail. Systems do.", category: "discipline" },
  { text: "Don't multitask. Stack-task with purpose.", category: "discipline" },
  { text: "Habit is the daughter of repetition.", category: "discipline" },
  { text: "Quiet hours are mastery hours.", category: "discipline" },
  { text: "Work expands to fill the time available — give it less.", category: "discipline" },
  { text: "Discipline is keeping the promises you made to yourself.", category: "discipline" },
  { text: "Show up tired. Showing up is what matters.", category: "discipline" },
  { text: "Make rules so you don't have to make decisions.", category: "discipline" },
  { text: "Avoid the people who tempt you off your plan.", category: "discipline" },
  { text: "If it isn't written down, it isn't real.", category: "discipline" },
  { text: "Cluttered notes hide clear concepts.", category: "discipline" },
  { text: "When in doubt, study.", category: "discipline" },
  { text: "Every habit makes its own gravity.", category: "discipline" },
  { text: "Read one paper a week — make it a ritual.", category: "discipline" },
  { text: "Same chair, same time, same outcome: progress.", category: "discipline" },
  { text: "Don't argue with your alarm. Move.", category: "discipline" },
  { text: "Discipline is just self-respect made visible.", category: "discipline" },
  {
    text: "Never miss twice — one slip is fine, two is a pattern.",
    category: "discipline",
    attribution: "James Clear",
  },
  { text: "Plans without discipline are wishes.", category: "discipline" },
  { text: "Preparation is invisible until results are obvious.", category: "discipline" },
  { text: "Good students study; great students review.", category: "discipline" },
  {
    text: "When you don't want to study, study for ten minutes. Often that's enough.",
    category: "discipline",
  },
  { text: "Discipline costs less than regret.", category: "discipline" },
  { text: "Show up before the version of you who doesn't want to.", category: "discipline" },
  { text: "Beat yesterday. That's enough.", category: "discipline" },
  { text: "Your phone is not your friend during study hours.", category: "discipline" },
  { text: "Do hard things on easy days.", category: "discipline" },
  { text: "Discipline is the silent path to becoming who you want to be.", category: "discipline" },
  { text: "Discipline is the muscle that makes everything else possible.", category: "discipline" },
  { text: "Hold the line. Read the line. Repeat the line.", category: "discipline" },
  { text: "Habits compound — for or against you.", category: "discipline" },
  {
    text: "Practice as if you're playing — playing is what you practiced.",
    category: "discipline",
  },
  { text: "Three pages a day equals a textbook a year.", category: "discipline" },
  { text: "Stack one good decision on top of another. That's a life.", category: "discipline" },
  { text: "Discipline is freedom from your moods.", category: "discipline" },
  { text: "When you want to quit, that's the lesson; finish the page.", category: "discipline" },
  { text: "Choose your hard. Studying hard or regret hard.", category: "discipline" },
  { text: "Discipline is the highest form of self-love.", category: "discipline" },
  {
    text: "Same time, same place, same intent. The brain finds the rhythm.",
    category: "discipline",
  },
  { text: "Your environment shapes you. Curate it ruthlessly.", category: "discipline" },
  { text: "Order your inputs and your outputs follow.", category: "discipline" },
  { text: "Discipline is patience with yourself.", category: "discipline" },
  { text: "Don't let perfection be the thief of progress.", category: "discipline" },
  { text: "If your study plan is rigid, your life will be brittle.", category: "discipline" },
  { text: "Plans must adapt; principles should not.", category: "discipline" },
  { text: "Rituals are repeated discipline. Build them.", category: "discipline" },
  { text: "Build the habit first. Outcomes follow.", category: "discipline" },
  { text: "Discipline is a daily vote for the person you want to become.", category: "discipline" },

  // ─────────────────────────────────────────────────────────────
  // SUCCESS (~100)
  // ─────────────────────────────────────────────────────────────
  {
    text: "Success is the sum of small efforts repeated day in and day out.",
    category: "success",
    attribution: "Robert Collier",
  },
  {
    text: "Success is not final, failure is not fatal: it is the courage to continue that counts.",
    category: "success",
    attribution: "Winston Churchill",
  },
  {
    text: "Success usually comes to those who are too busy to be looking for it.",
    category: "success",
    attribution: "Henry David Thoreau",
  },
  {
    text: "Success usually comes after dozens of failures most people never see.",
    category: "success",
  },
  { text: "Trade comfortable for capable.", category: "success" },
  {
    text: "Success is walking from failure to failure with no loss of enthusiasm.",
    category: "success",
    attribution: "Winston Churchill",
  },
  {
    text: "I find that the harder I work, the more luck I seem to have.",
    category: "success",
    attribution: "Thomas Jefferson",
  },
  {
    text: "Success is doing ordinary things extraordinarily well.",
    category: "success",
    attribution: "Jim Rohn",
  },
  {
    text: "Success comes from knowing that you did your best to become the best you are capable of becoming.",
    category: "success",
    attribution: "John Wooden",
  },
  {
    text: "The successful warrior is the average man, with laser-like focus.",
    category: "success",
    attribution: "Bruce Lee",
  },
  {
    text: "Success is liking yourself, liking what you do, and liking how you do it.",
    category: "success",
    attribution: "Maya Angelou",
  },
  {
    text: "The road to success is always under construction.",
    category: "success",
    attribution: "Lily Tomlin",
  },
  {
    text: "Success seems to be connected with action. Successful people keep moving.",
    category: "success",
    attribution: "Conrad Hilton",
  },
  {
    text: "If you want to be successful, be willing to look stupid temporarily while you learn.",
    category: "success",
  },
  {
    text: "Success is getting what you want; happiness is wanting what you get.",
    category: "success",
    attribution: "Dale Carnegie",
  },
  {
    text: "There is no elevator to success. You have to take the stairs.",
    category: "success",
    attribution: "Zig Ziglar",
  },
  {
    text: "Try not to become a person of success, but rather a person of value.",
    category: "success",
    attribution: "Albert Einstein",
  },
  {
    text: "The secret of success is constancy of purpose.",
    category: "success",
    attribution: "Benjamin Disraeli",
  },
  { text: "Movement is the foundation of every meaningful outcome.", category: "success" },
  {
    text: "You miss 100% of the shots you don't take.",
    category: "success",
    attribution: "Wayne Gretzky",
  },
  {
    text: "The best revenge is massive success.",
    category: "success",
    attribution: "Frank Sinatra",
  },
  {
    text: "Success is how high you bounce when you hit bottom.",
    category: "success",
    attribution: "George S. Patton",
  },
  {
    text: "Success consists of going from failure to failure without loss of enthusiasm.",
    category: "success",
    attribution: "Winston Churchill",
  },
  {
    text: "Failure is the condiment that gives success its flavour.",
    category: "success",
    attribution: "Truman Capote",
  },
  {
    text: "To succeed in life, you need three things: a wishbone, a backbone, and a funny bone.",
    category: "success",
    attribution: "Reba McEntire",
  },
  {
    text: "Success is most often achieved by those who don't know that failure is inevitable.",
    category: "success",
    attribution: "Coco Chanel",
  },
  { text: "Done is the engine of more.", category: "success", attribution: "Bre Pettis" },
  {
    text: "There are no traffic jams on the extra mile.",
    category: "success",
    attribution: "Roger Staubach",
  },
  {
    text: "Success is what happens after you've survived all your disappointments.",
    category: "success",
    attribution: "Sylvester Stallone",
  },
  {
    text: "Always do your best. What you plant now, you will harvest later.",
    category: "success",
    attribution: "Og Mandino",
  },
  {
    text: "It is hard to fail, but it is worse never to have tried to succeed.",
    category: "success",
    attribution: "Theodore Roosevelt",
  },
  {
    text: "Success is not the result of spontaneous combustion. You must set yourself on fire.",
    category: "success",
    attribution: "Arnold H. Glasow",
  },
  {
    text: "Eighty percent of success is showing up.",
    category: "success",
    attribution: "Woody Allen",
  },
  {
    text: "Aim for the moon. If you miss, you may hit a star.",
    category: "success",
    attribution: "W. Clement Stone",
  },
  { text: "Don't be afraid to fail. Be afraid not to try.", category: "success" },
  {
    text: "Big shots are only little shots who keep shooting.",
    category: "success",
    attribution: "Christopher Morley",
  },
  {
    text: "Success is no accident. It is hard work, perseverance, learning, studying, sacrifice, and most of all, love.",
    category: "success",
    attribution: "Pelé",
  },
  { text: "Success is liking what you do — and liking who you become.", category: "success" },
  {
    text: "Success usually comes the day after almost everyone else has given up.",
    category: "success",
  },
  { text: "Today's accomplishment is tomorrow's foundation.", category: "success" },
  { text: "Confidence comes from preparation, not pep talks.", category: "success" },
  { text: "Quiet wins compound louder than loud ones.", category: "success" },
  { text: "Knowledge accumulates. So do small wins.", category: "success" },
  {
    text: "Master the basics first. Brilliance is well-rehearsed fundamentals.",
    category: "success",
  },
  { text: "If you want unusual results, do unusual things.", category: "success" },
  { text: "Success is invisible until it isn't.", category: "success" },
  { text: "Don't measure progress in days. Measure in chapters.", category: "success" },
  { text: "Make the goal real. Write it down.", category: "success" },
  { text: "Trade the trivial for the transformative.", category: "success" },
  { text: "Tomorrow's expert was today's apprentice.", category: "success" },
  { text: "Earn it twice — once by learning, once by teaching it back.", category: "success" },
  { text: "Read deeply. Recall often. Apply daily.", category: "success" },
  { text: "Aim narrow. Hit deep.", category: "success" },
  { text: "If you can teach it, you know it.", category: "success" },
  { text: "Big problems get solved one small page at a time.", category: "success" },
  { text: "Don't wait for permission to be excellent.", category: "success" },
  { text: "Lower the noise, raise the standard.", category: "success" },
  { text: "Trust the process; verify the progress.", category: "success" },
  { text: "Doctors are made by patients, but taught by chapters.", category: "success" },
  { text: "Read like your patients depend on it. They will.", category: "success" },
  { text: "The student who reviews wins the exam.", category: "success" },
  { text: "Mark today on the calendar — you got 1% better.", category: "success" },
  { text: "Reps make pros. Skipping reps makes regret.", category: "success" },
  { text: "You're closer than you think. Keep reading.", category: "success" },
  { text: "Hard now, easy later.", category: "success" },
  { text: "When in doubt, do the next right thing.", category: "success" },
  {
    text: "Better question, better answer; better answer, better understanding.",
    category: "success",
  },
  {
    text: "If you can explain it simply, you understand it well.",
    category: "success",
    attribution: "Albert Einstein",
  },
  { text: "Mastery is a series of small mistakes made carefully.", category: "success" },
  { text: "Don't compare your chapter one to someone's chapter twenty.", category: "success" },
  { text: "Goals win silver. Habits win gold.", category: "success" },
  { text: "Success isn't loud — it's daily.", category: "success" },
  { text: "Be patient with results, impatient with effort.", category: "success" },
  { text: "Hold your standard, even when no one's watching.", category: "success" },
  { text: "Success is the by-product of consistent attention.", category: "success" },
  { text: "Today's small win is tomorrow's confidence.", category: "success" },
  { text: "Mediocre is just mastery without practice.", category: "success" },
  { text: "Reps over rest, but never instead of rest.", category: "success" },
  { text: "Success rewards the curious as much as the hardworking.", category: "success" },
  { text: "Trust your reps. They paid for the result.", category: "success" },
  { text: "Mastery looks easy from the outside; that's the point.", category: "success" },
  { text: "If your goal scares you a little, it's about right.", category: "success" },
  { text: "Build the habit. The wins will find you.", category: "success" },
  { text: "Curiosity is the engine of success.", category: "success" },
  { text: "If you can keep going when others stop, you've already won.", category: "success" },
  { text: "Success leaves a trail of small daily decisions.", category: "success" },
  { text: "Don't postpone joy on the way to the win.", category: "success" },
  { text: "Excellence is a habit, not an event.", category: "success" },
  { text: "Be so good they can't ignore you.", category: "success", attribution: "Steve Martin" },
  {
    text: "Champions are made of something they have deep inside — a desire, a dream, a vision.",
    category: "success",
    attribution: "Muhammad Ali",
  },
  {
    text: "I've failed over and over and over again in my life. And that is why I succeed.",
    category: "success",
    attribution: "Michael Jordan",
  },
  {
    text: "The way to get started is to quit talking and begin doing.",
    category: "success",
    attribution: "Walt Disney",
  },
  {
    text: "Success doesn't come from what you do occasionally; it comes from what you do consistently.",
    category: "success",
    attribution: "Marie Forleo",
  },
  { text: "What you stay focused on grows.", category: "success" },
  { text: "Don't envy success. Engineer it.", category: "success" },
  { text: "Build skills the market can't ignore.", category: "success" },
  { text: "If you want a different result, change a different input.", category: "success" },
  { text: "Compounding is real. Show up.", category: "success" },
  { text: "Daily action beats yearly resolutions.", category: "success" },
  { text: "Hard work in private. Success in public.", category: "success" },

  // ─────────────────────────────────────────────────────────────
  // REST / SLEEP (~100)
  // ─────────────────────────────────────────────────────────────
  { text: "Sleep is the best meditation.", category: "rest", attribution: "Dalai Lama" },
  {
    text: "Rest when you're weary. Refresh and renew yourself, your body, your mind, your spirit. Then get back to work.",
    category: "rest",
    attribution: "Ralph Marston",
  },
  {
    text: "Sleep is the golden chain that ties health and our bodies together.",
    category: "rest",
    attribution: "Thomas Dekker",
  },
  {
    text: "Take rest; a field that has rested gives a bountiful crop.",
    category: "rest",
    attribution: "Ovid",
  },
  {
    text: "Sleep is that golden chain that ties our health and our bodies together.",
    category: "rest",
  },
  {
    text: "Almost everything will work again if you unplug it for a few minutes — including you.",
    category: "rest",
    attribution: "Anne Lamott",
  },
  { text: "Rest is not idleness. It is the basis of effort.", category: "rest" },
  { text: "Sleep is the brain's housekeeping. Don't skip it.", category: "rest" },
  { text: "When you cannot solve a problem, sleep on it.", category: "rest" },
  { text: "A well-rested doctor saves more lives than an exhausted one.", category: "rest" },
  { text: "Memory consolidates while you sleep — give it time.", category: "rest" },
  { text: "Eight hours of sleep is the cheapest study aid you'll ever buy.", category: "rest" },
  { text: "An hour of deep sleep beats two hours of distracted study.", category: "rest" },
  { text: "Naps are not lazy. They're maintenance.", category: "rest" },
  { text: "If you're tired, learn to rest. Not to quit.", category: "rest", attribution: "Banksy" },
  { text: "Rest is a weapon.", category: "rest" },
  { text: "Sleep is not optional. It is operational.", category: "rest" },
  {
    text: "The brain you study with tonight is built by the sleep you got last night.",
    category: "rest",
  },
  { text: "Burnout is not a badge.", category: "rest" },
  { text: "Sleep is the new productivity hack — that we keep forgetting.", category: "rest" },
  { text: "You can't pour from an empty cup. Sleep first.", category: "rest" },
  { text: "Save the all-nighter for an emergency. Most exams aren't one.", category: "rest" },
  { text: "Caffeine is a mask, not a substitute.", category: "rest" },
  { text: "Wisdom belongs to the well-rested.", category: "rest" },
  { text: "Phone outside the bedroom — your brain says thank you.", category: "rest" },
  { text: "Sleep before midnight is twice as restorative as sleep after.", category: "rest" },
  { text: "A nap is a small reset. Take one.", category: "rest" },
  { text: "Rest hard so you can study hard.", category: "rest" },
  { text: "REM doesn't negotiate. Honour it.", category: "rest" },
  { text: "Sleep is not a luxury. It's a clinical necessity.", category: "rest" },
  { text: "Burning the candle at both ends only ends the candle sooner.", category: "rest" },
  { text: "Rest is a part of training, not a break from it.", category: "rest" },
  { text: "The brain learns while the body sleeps.", category: "rest" },
  { text: "Tired brains forget. Rested brains recall.", category: "rest" },
  { text: "Sleep deprivation is a study deficit.", category: "rest" },
  { text: "Sleeping less doesn't mean studying more — usually the opposite.", category: "rest" },
  { text: "Make your bed your cathedral, not your office.", category: "rest" },
  { text: "Dim the screen, breathe slowly, and let go of today.", category: "rest" },
  { text: "Take the Sunday off. The textbook will be there Monday.", category: "rest" },
  { text: "A walk is also study — for the parts that need silence.", category: "rest" },
  { text: "If you can't focus, rest. Don't grind.", category: "rest" },
  { text: "Rest is permission, not punishment.", category: "rest" },
  { text: "Slow down to learn faster.", category: "rest" },
  { text: "Sleep is when learning gets locked in.", category: "rest" },
  { text: "Don't trade tomorrow's energy for tonight's anxiety.", category: "rest" },
  { text: "The body keeps score. Pay it back with sleep.", category: "rest" },
  { text: "Pause before you crash; rest before you must.", category: "rest" },
  { text: "If you can't remember, sleep. Then read again.", category: "rest" },
  { text: "Coffee is borrowed energy; sleep is owned energy.", category: "rest" },
  { text: "Pull a book to bed, but close it before midnight.", category: "rest" },
  { text: "Quiet evenings make sharper mornings.", category: "rest" },
  { text: "Rest deeply, return refreshed, recall sharply.", category: "rest" },
  { text: "Stress disappears in the dark of a good night's sleep.", category: "rest" },
  { text: "An afternoon nap fixes more than caffeine.", category: "rest" },
  { text: "If you've been studying for four hours, take twenty minutes off.", category: "rest" },
  { text: "Boredom is your brain asking for a break, not for a phone.", category: "rest" },
  { text: "Walk. Breathe. Re-enter the page.", category: "rest" },
  { text: "Sleep is not negotiable; it is non-fungible.", category: "rest" },
  { text: "There is no medal for the most exhausted student.", category: "rest" },
  { text: "Even Olympians take rest days.", category: "rest" },
  { text: "Recovery isn't lazy — it's strategic.", category: "rest" },
  { text: "Bed by 11 makes 7 AM possible.", category: "rest" },
  { text: "Honour the dark with the light off.", category: "rest" },
  { text: "Treat your sleep like an exam. Show up on time.", category: "rest" },
  { text: "Rest, recover, return — three Rs of every champion.", category: "rest" },
  { text: "Hydrate, walk, sleep — your three free study aids.", category: "rest" },
  { text: "If you're falling asleep over your book, listen to your body.", category: "rest" },
  { text: "Tomorrow's you is asking today's you to please go to bed.", category: "rest" },
  { text: "Sleep is the closest thing we have to a reset button.", category: "rest" },
  { text: "Skip a chapter, never skip a sleep.", category: "rest" },
  { text: "Don't borrow rest from yourself — you can't pay it back.", category: "rest" },
  { text: "Power down screens an hour before bed.", category: "rest" },
  { text: "Even the brain needs nap-time.", category: "rest" },
  { text: "Burnout writes worse exams than ignorance.", category: "rest" },
  { text: "Rest your eyes for twenty seconds every twenty minutes.", category: "rest" },
  { text: "A stretch every hour beats a slump in the evening.", category: "rest" },
  { text: "Sleep is part of studying — not an interruption to it.", category: "rest" },
  { text: "If everything seems hard, sleep first. Then decide.", category: "rest" },
  { text: "Reading sleepy is wasting paper.", category: "rest" },
  { text: "Recovery is when adaptation happens.", category: "rest" },
  { text: "A student who rests well, learns well.", category: "rest" },
  { text: "Saying no to one more chapter is sometimes the wiser yes.", category: "rest" },
  { text: "Stop where you are if you've stopped retaining.", category: "rest" },
  { text: "When you feel guilty for resting, you needed it most.", category: "rest" },
  { text: "Pause to breathe. Patients will, too.", category: "rest" },
  { text: "Build a wind-down ritual. Tea. Lights low. Phone away.", category: "rest" },
  { text: "Even a five-minute eye-close counts.", category: "rest" },
  { text: "Sleep heals what cramming breaks.", category: "rest" },
  { text: "Don't work harder than your sleep allows.", category: "rest" },
  { text: "A walk outdoors counts as deep work.", category: "rest" },
  { text: "Disconnect to reconnect.", category: "rest" },
  { text: "Switch off so you can switch on later.", category: "rest" },
  {
    text: "Sleep deprivation is a clinical syndrome — diagnose and treat your own.",
    category: "rest",
  },
  { text: "Tomorrow needs you well-rested. Tonight will agree.", category: "rest" },
  { text: "Even your textbook needs a closing.", category: "rest" },
  { text: "Set a study end-time. Honour it.", category: "rest" },
  { text: "Saturday afternoon naps are sacred.", category: "rest" },
  { text: "There is no productivity without recovery.", category: "rest" },
  { text: "Rest is how your brain compounds today's reading.", category: "rest" },
  { text: "Dream, then study tomorrow with new clarity.", category: "rest" },
  { text: "Sleep is the bridge from input to insight.", category: "rest" },
];

/**
 * Returns a random quote. Uniformly distributed across all entries —
 * not weighted by category. The dashboard server-renders, so this is
 * called per request and produces a fresh quote on each navigation.
 */
export function pickRandomQuote(): Quote {
  const i = Math.floor(Math.random() * QUOTES.length);
  return QUOTES[i];
}
